
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'poc_s3_glue_spectrum_dbt_redshift'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'poc_s3_glue_spectrum_dbt_redshift'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"

on-run-start: "{{ ejecucion_proyecto(1) }}"
on-run-end: "{{ ejecucion_proyecto(3) }}"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:

  poc_s3_glue_spectrum_dbt_redshift:
    # Config indicated by + and applies to all files under models/raw/
    raw:
      +materialized: table
      +schema: raw
#      +pre-hook: "{{ ejecucion_pre_modelo(this) }}"
#      +post-hook: "{{ ejecucion_modelo(this) }}"
    but:
      +materialized: table
      +schema: but
#      +pre-hook: "{{ ejecucion_pre_modelo(this) }}"
#      +post-hook: "{{ ejecucion_modelo(this) }}"
    arc:
      +materialized: table
      +schema: arc
#      +pre-hook: "{{ ejecucion_pre_modelo(this) }}"
#      +post-hook: "{{ ejecucion_modelo(this) }}"
